export const BLOOD_GROUPS = [
  'A+',
  'A-',
  'B+',
  'B-',
  'AB+',
  'AB-',
  'O+',
  'O-',
] as const;
export type BloodGroup = (typeof BLOOD_GROUPS)[number];

export const DISTRICTS = [
  { id: 'rangpur', name: 'Rangpur' },
  { id: 'dinajpur', name: 'Dinajpur' },
  { id: 'kurigram', name: 'Kurigram' },
  { id: 'lalmonirhat', name: 'Lalmonirhat' },
  { id: 'nilphamari', name: 'Nilphamari' },
  { id: 'gaibandha', name: 'Gaibandha' },
  { id: 'thakurgaon', name: 'Thakurgaon' },
  { id: 'panchagarh', name: 'Panchagarh' },
] as const;

export const UPAZILAS = [
  { id: 'rangpur_sadar', district_id: 'rangpur', name: 'Rangpur Sadar' },
  { id: 'rangpur_gangachara', district_id: 'rangpur', name: 'Gangachara' },
  { id: 'rangpur_kaunia', district_id: 'rangpur', name: 'Kaunia' },
  { id: 'rangpur_pirganj', district_id: 'rangpur', name: 'Pirganj' },
  { id: 'rangpur_taraganj', district_id: 'rangpur', name: 'Taraganj' },
  { id: 'rangpur_badarganj', district_id: 'rangpur', name: 'Badarganj' },
  { id: 'rangpur_mithapukur', district_id: 'rangpur', name: 'Mithapukur' },
  { id: 'rangpur_city', district_id: 'rangpur', name: 'Rangpur City' },
  { id: 'rangpur_paglapir', district_id: 'rangpur', name: 'Paglapir' },
  { id: 'dinajpur_sadar', district_id: 'dinajpur', name: 'Dinajpur Sadar' },
  { id: 'dinajpur_birampur', district_id: 'dinajpur', name: 'Birampur' },
  { id: 'dinajpur_birganj', district_id: 'dinajpur', name: 'Birganj' },
  { id: 'dinajpur_biral', district_id: 'dinajpur', name: 'Biral' },
  { id: 'dinajpur_bochaganj', district_id: 'dinajpur', name: 'Bochaganj' },
  { id: 'dinajpur_chirirbandar', district_id: 'dinajpur', name: 'Chirirbandar' },
  { id: 'dinajpur_phulbari', district_id: 'dinajpur', name: 'Phulbari' },
  { id: 'dinajpur_ghoraghat', district_id: 'dinajpur', name: 'Ghoraghat' },
  { id: 'dinajpur_hakimpur', district_id: 'dinajpur', name: 'Hakimpur' },
  { id: 'dinajpur_kaharole', district_id: 'dinajpur', name: 'Kaharole' },
  { id: 'dinajpur_khansama', district_id: 'dinajpur', name: 'Khansama' },
  { id: 'dinajpur_nawabganj', district_id: 'dinajpur', name: 'Nawabganj' },
  { id: 'dinajpur_parbatipur', district_id: 'dinajpur', name: 'Parbatipur' },
  { id: 'kurigram_sadar', district_id: 'kurigram', name: 'Kurigram Sadar' },
  { id: 'kurigram_ulipur', district_id: 'kurigram', name: 'Ulipur' },
  { id: 'kurigram_chilmari', district_id: 'kurigram', name: 'Chilmari' },
  { id: 'kurigram_rajarhat', district_id: 'kurigram', name: 'Rajarhat' },
  { id: 'kurigram_phulbari', district_id: 'kurigram', name: 'Phulbari' },
  { id: 'kurigram_nageshwari', district_id: 'kurigram', name: 'Nageshwari' },
  { id: 'kurigram_bhurungamari', district_id: 'kurigram', name: 'Bhurungamari' },
  { id: 'kurigram_rowmari', district_id: 'kurigram', name: 'Rowmari' },
  { id: 'kurigram_char_rajibpur', district_id: 'kurigram', name: 'Char Rajibpur' },
  { id: 'lalmonirhat_sadar', district_id: 'lalmonirhat', name: 'Lalmonirhat Sadar' },
  { id: 'lalmonirhat_aditmari', district_id: 'lalmonirhat', name: 'Aditmari' },
  { id: 'lalmonirhat_hatibandha', district_id: 'lalmonirhat', name: 'Hatibandha' },
  { id: 'lalmonirhat_kaliganj', district_id: 'lalmonirhat', name: 'Kaliganj' },
  { id: 'lalmonirhat_patgram', district_id: 'lalmonirhat', name: 'Patgram' },
  { id: 'nilphamari_sadar', district_id: 'nilphamari', name: 'Nilphamari Sadar' },
  { id: 'nilphamari_dimla', district_id: 'nilphamari', name: 'Dimla' },
  { id: 'nilphamari_domar', district_id: 'nilphamari', name: 'Domar' },
  { id: 'nilphamari_jaldhaka', district_id: 'nilphamari', name: 'Jaldhaka' },
  { id: 'nilphamari_kishoreganj', district_id: 'nilphamari', name: 'Kishoreganj' },
  { id: 'nilphamari_saidpur', district_id: 'nilphamari', name: 'Saidpur' },
  { id: 'gaibandha_sadar', district_id: 'gaibandha', name: 'Gaibandha Sadar' },
  { id: 'gaibandha_sadullapur', district_id: 'gaibandha', name: 'Sadullapur' },
  { id: 'gaibandha_palashbari', district_id: 'gaibandha', name: 'Palashbari' },
  { id: 'gaibandha_gobindaganj', district_id: 'gaibandha', name: 'Gobindaganj' },
  { id: 'gaibandha_sundarganj', district_id: 'gaibandha', name: 'Sundarganj' },
  { id: 'gaibandha_fulchhari', district_id: 'gaibandha', name: 'Fulchhari' },
  { id: 'gaibandha_shaghata', district_id: 'gaibandha', name: 'Shaghata' },
  { id: 'thakurgaon_sadar', district_id: 'thakurgaon', name: 'Thakurgaon Sadar' },
  { id: 'thakurgaon_baliadangi', district_id: 'thakurgaon', name: 'Baliadangi' },
  { id: 'thakurgaon_haripur', district_id: 'thakurgaon', name: 'Haripur' },
  { id: 'thakurgaon_pirganj', district_id: 'thakurgaon', name: 'Pirganj' },
  { id: 'thakurgaon_ranisankail', district_id: 'thakurgaon', name: 'Ranisankail' },
  { id: 'panchagarh_sadar', district_id: 'panchagarh', name: 'Panchagarh Sadar' },
  { id: 'panchagarh_atwari', district_id: 'panchagarh', name: 'Atwari' },
  { id: 'panchagarh_boda', district_id: 'panchagarh', name: 'Boda' },
  { id: 'panchagarh_debiganj', district_id: 'panchagarh', name: 'Debiganj' },
  { id: 'panchagarh_tetulia', district_id: 'panchagarh', name: 'Tetulia' },
];

export function getUpazilasByDistrict(districtId: string) {
  return UPAZILAS.filter((u) => u.district_id === districtId);
}