export const Strings = {
  appName: 'Trinomul Blood Bank',
  region: 'Rangpur',
  tagline: 'Rangpur Division Blood Network',
  heroTitle: 'Donate Blood, Save Lives',
  heroSubtitle: 'Connect with voluntary blood donors across Rangpur division.',
  heroBadge: 'Rangpur Division Blood Network',
  findDonorTitle: 'Find a Blood Donor',
  aiSearch: 'AI-powered search',
  bloodGroup: 'Blood Group',
  district: 'District',
  searchPlaceholder: 'Type blood group, area, name or phone…',
  searchBtn: 'Search',
  findDonors: 'Find Donors',
  requestBlood: 'Request Blood',
  bloodMap: 'Blood Map',
  leaderboard: 'Leaderboard',
  becomeDonor: 'Become a Donor',
  home: 'Home',
  donors: 'Donors',
  requests: 'Requests',
  map: 'Map',
  profile: 'Profile',
  comingSoon: 'Coming soon',
  nearMe: 'Near Me',
  nearMeActive: 'Nearest First',
  locating: 'Locating…',
  locationDenied: 'Location permission denied',
  allGroups: 'All',
  searchDonors: 'Search donors by name, area, phone…',
  filterByDistrict: 'Filter by district',
  available: 'Available',
  coolingDown: 'Cooling Down',
  unavailable: 'Unavailable',
  contact: 'Call',
  donations: 'Donations',
  donorSince: 'Since',
  verified: 'Verified donor',
  noDonorsFound: 'No donors found',
  noDonorsHint: 'Try changing filters or search query',
  resultsCount: 'donors found',
  sortByDistance: 'Sorted by distance',
  eligibleFrom: 'Eligible from',
  bloodRequests: 'Blood Requests',
  postRequest: 'Post a Request',
  searchRequests: 'Search by patient, hospital, area…',
  allUrgency: 'All',
  critical: 'Critical',
  urgent: 'Urgent',
  normal: 'Normal',
  noRequestsFound: 'No requests found',
  noRequestsHint: 'Be the first to post a blood request',
  requestDetails: 'Request Details',
  patientName: 'Patient Name',
  bloodGroupRequired: 'Blood Group',
  unitsNeeded: 'Units Needed',
  urgencyLevel: 'Urgency Level',
  whenNeeded: 'When Needed',
  hospitalName: 'Hospital Name',
  hospitalAddress: 'Hospital Address',
  contactNumber: 'Contact Number',
  whatsappNumber: 'WhatsApp Number (optional)',
  reasonOptional: 'Reason (optional)',
  reasonPlaceholder: 'e.g. Emergency surgery, anemia…',
  submitRequest: 'Submit Request',
  submitting: 'Submitting…',
  requestSubmitted: 'Request Submitted!',
  requestSubmittedHint: 'Your blood request has been posted. Donors will be notified soon.',
  postAnother: 'Post Another Request',
  selectBloodGroup: 'Select blood group',
  selectDistrict: 'Select district',
  selectUpazila: 'Select upazila',
  selectUrgency: 'Select urgency',
  selectWhenNeeded: 'Select when needed',
  neededNow: 'Now',
  neededToday: 'Today',
  neededTomorrow: 'Tomorrow',
  neededDayAfter: 'Day After',
  neededScheduled: 'Scheduled',
  backToRequests: 'Back to Requests',
  loadingDonors: 'Loading donors…',
  loadingRequests: 'Loading requests…',
  offlineMode: 'Offline — showing sample data',
  offlineCached: 'Offline — showing cached data',
  liveMode: 'Live',
  trackingCode: 'Tracking Code',
  trackingCodeHint: 'Save this code to track your request status',
  submitError: 'Failed to submit. Check your connection and try again.',
  retry: 'Retry',
  leaderboardTitle: 'Donor Leaderboard',
  leaderboardSubtitle: 'Top donors across Rangpur division',
  rank: 'Rank',
  livesSaved: 'lives',
  referrals: 'referrals',
  donationCount: 'donations',
  noLeaderboard: 'No leaderboard data',
  loadingLeaderboard: 'Loading leaderboard…',
  mapTitle: 'Blood Map',
  mapSubtitle: 'Donors and requests near you',
  mapDonors: 'Donors',
  mapRequests: 'Requests',
  mapAll: 'All',
  noLocation: 'Enable location to see nearby donors and requests',
  enableLocation: 'Enable Location',
  profileTitle: 'Profile',
  becomeDonorTitle: 'Become a Donor',
  becomeDonorSubtitle: 'Register as a voluntary blood donor',
  fullName: 'Full Name (English)',
  fullNameBn: 'Full Name (Bangla)',
  phone: 'Phone Number',
  alternativePhone: 'Alternative Phone (optional)',
  whatsappNumberField: 'WhatsApp Number (optional)',
  dateOfBirth: 'Date of Birth',
  gender: 'Gender',
  male: 'Male',
  female: 'Female',
  other: 'Other',
  address: 'Address',
  union: 'Union (optional)',
  consent: 'I agree to be contacted for blood donation',
  registerDonor: 'Register as Donor',
  registering: 'Registering…',
  registrationSuccess: 'Registration Successful!',
  registrationSuccessHint: 'Thank you for registering. You will be contacted soon.',
  registeredAlready: 'Already a donor? View your profile',
  profileGuest: 'You are not signed in',
  profileGuestHint: 'Register as a donor or sign in to manage your profile',

  sos: 'SOS',
  sosEmergency: 'EMERGENCY',
  sosCancel: 'CANCEL',
  sosStarting: 'Starting Emergency SOS in',
  sosActivated: 'EMERGENCY SOS ACTIVATED',
  sosSubtitle: 'This will post a critical blood request immediately',
  sosBloodGroup: 'Blood Group Needed',
  sosPatientName: 'Patient Name',
  sosLocation: 'Hospital / Location',
  sosContact: 'Your Contact Number',
  sosReason: 'Emergency Details',
  sosReasonPlaceholder: 'e.g. Accident, surgery, critical condition…',
  sosSubmit: 'SEND EMERGENCY SOS',
  sosSending: 'Sending SOS…',
  sosSuccess: 'SOS SENT!',
  sosSuccessHint: 'Emergency request posted. Donors will be notified immediately.',
  sos999: 'Call 999',
  sosWarning: 'This will alert ALL compatible donors in your area',
  sosSelectGroup: 'Select blood group first',
  login: 'Sign In',
  loginTitle: 'Welcome Back',
  loginSubtitle: 'Sign in to manage your profile',
  email: 'Email',
  password: 'Password',
  dontHaveAccount: 'Don\'t have an account? ',
  haveAccount: 'Already have an account? ',
  signup: 'Sign Up',
  signupTitle: 'Create Account',
  signupSubtitle: 'Sign up to manage your profile',
  logout: 'Log Out',
  weightKg: 'Weight (kg)',
  occupation: 'Occupation (optional)',
  preferredContact: 'Preferred Contact',
  call: 'Call',
  whatsapp: 'WhatsApp',
  either: 'Either',
  hbLevel: 'Hemoglobin Level (g/dL)',
  lastHbTestDate: 'Last HB Test Date',
  lastDonationDate: 'Last Donation Date',
  hasChronicDisease: 'I have a chronic disease',
  diseaseDetails: 'Please describe (optional)',
  copyPhone: 'Copy',
  loginError: 'Login failed. Please try again.',
  signupError: 'Signup failed. Please try again.',
  community: 'Community',
  communityTitle: 'Community',
  communitySubtitle: 'Connect with blood donors and requests',
  scanner: 'Scanner',
  scannerTitle: 'QR Scanner',
  scannerSubtitle: 'Scan QR codes to find donors and requests',
  scanQr: 'Scan QR Code',
  scanHint: 'Point the camera at a QR code',
  scanError: 'Failed to scan. Try again.',
} as const;